source 'https://bitbucket.org/agens/agenspodspec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'IVYPool', :path => '../IVYPool.podspec'

target :IVYPoolDemoTests do
    pod 'Expecta', '~> 1.0.2'
end


